// RegFreeComNativeImplementer.idl : IDL source for RegFreeComNativeImplementer
//

// This file will be processed by the MIDL tool to
// produce the type library (RegFreeComNativeImplementer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(156489B3-1745-48D3-9FAA-2C58DBA01D53),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IImplementer : IDispatch{
};
[
	uuid(DA4AE577-B161-4D4A-9E55-0221D949203C),
	version(1.0),
]
library RegFreeComNativeImplementerLib
{
	importlib("stdole2.tlb");
	[
		uuid(538ECD5D-8A57-4F1C-AEB1-EBC425641F0B)		
	]
	coclass Implementer
	{
		[default] interface IImplementer;
	};
};

